service: node-simple-http-endpoint # NOTE: Don't put the word "google" in here

provider:
  name: google
  region: us-east4
  runtime: nodejs10
  project: rhok11-stopgap
  credentials: ~\.gcloud\rhok11-stopgap-a3395605b3de.json # path must be absolute

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  getAllRampRequests:
    handler: getAllRampRequests
    events:
      - http: get
  getRampRequest:
    handler: getRampRequest
    events:
      - http: get
  uploadRampRequest:
    handler: uploadRampRequest
    events:
      - http: post
  getFile:
    handler: getFile
    events:
      - http: get
